-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 16, 2023 at 10:09 AM
-- Server version: 10.4.24-MariaDB
-- PHP Version: 8.1.6

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `pweb`
--

-- --------------------------------------------------------

--
-- Table structure for table `perpustakaan`
--

CREATE TABLE `perpustakaan` (
  `id` int(11) NOT NULL,
  `judul` varchar(500) NOT NULL,
  `penerbit` varchar(500) NOT NULL,
  `tahun` varchar(500) NOT NULL,
  `cover` varchar(500) NOT NULL,
  `jenis` varchar(500) NOT NULL,
  `kondisi` varchar(500) NOT NULL,
  `status` varchar(500) NOT NULL,
  `story` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `perpustakaan`
--

INSERT INTO `perpustakaan` (`id`, `judul`, `penerbit`, `tahun`, `cover`, `jenis`, `kondisi`, `status`, `story`) VALUES
(77, '9 bulan penuh keajaiban', 'Penerbit Utama', '2021', '9 bulan penuh keajaiban.jpg', 'panduan kehamilan', 'Baru', 'ada', 'Buku ini adalah panduan praktis yang berisi informasi penting dan lengkap bagi ibu hamil selama 9 bulan kehamilan mereka. Mulai dari tahap awal kehamilan hingga persiapan menjelang kelahiran, buku ini memberikan pengetahuan yang dibutuhkan untuk menjalani masa kehamilan dengan sehat, aman, dan penuh kebahagiaan. Di dalamnya terdapat informasi mengenai perubahan fisik dan emosional yang terjadi pada ibu hamil, perkembangan janin, nutrisi yang dibutuhkan, olahraga yang disarankan, perawatan prenat'),
(78, '20 obat terpopuler penurun pertensi', 'Penerbit Kesehatan Terkemuka', '2022', '20 obat terpopuler penurun pertensi.JPG', 'panduan kesehatan', 'Bagus', 'tidak', 'Buku ini adalah panduan komprehensif yang mengulas 20 obat terpopuler yang digunakan untuk menurunkan tekanan darah tinggi (hipertensi). Setiap obat dijelaskan secara mendetail, termasuk mekanisme kerja, dosis yang direkomendasikan, efek samping yang mungkin terjadi, dan interaksi obat dengan makanan atau obat lain. Buku ini juga memberikan informasi tentang pentingnya pengelolaan tekanan darah tinggi, dampaknya terhadap kesehatan, serta saran-saran gaya hidup sehat yang dapat mendukung pengobat'),
(79, '20 pahlawan nasional', 'Penerbit Sejarah Indonesia', '2021', '20 pahlawan nasional.JPG', 'sejarah', 'Bekas', 'ada', 'Buku ini mengangkat kisah inspiratif dari 20 pahlawan nasional yang berperan penting dalam sejarah Indonesia. Setiap pahlawan diceritakan secara singkat dan menarik, termasuk latar belakang kehidupan, perjuangan, serta kontribusi yang mereka berikan dalam memperjuangkan kemerdekaan dan membangun negara. Buku ini menggambarkan semangat kepahlawanan, dedikasi, dan pengorbanan yang menginspirasi generasi masa kini untuk mencintai dan memperjuangkan negara mereka.'),
(80, '26 kiat tubuh sehat dan bugar', 'Penerbit Kesehatan Sehat Sentosa', '2022', '26 kiat tbuh sehat dan bugar.jpg', 'panduan kesehatan', 'Bagus', 'ada', 'Buku ini berisi 26 kiat praktis dan efektif untuk menjaga kesehatan dan kebugaran tubuh. Setiap kiat disajikan dengan penjelasan yang jelas dan ringkas, serta dilengkapi dengan langkah-langkah yang dapat diikuti untuk menerapkan kiat tersebut dalam kehidupan sehari-hari. Buku ini mencakup berbagai aspek kesehatan, seperti pola makan sehat, olahraga, tidur yang cukup, manajemen stres, dan tips untuk meningkatkan energi dan kebugaran secara keseluruhan. Dengan mengikuti kiat-kiat yang disajikan da'),
(82, '99 misteri terbesar di dunia sepanjang masa', 'Penerbit Mysteria', '2022', '99 misteri terbesar di dunia sepanjang masa.JPG', 'nonfiksi', 'Baru', 'ada', 'Buku ini mengungkapkan 99 misteri terbesar yang belum terpecahkan di dunia sepanjang masa. Dari piramida Mesir kuno yang megah hingga Segitiga Bermuda yang misterius, buku ini menjelajahi berbagai kejadian dan tempat yang penuh teka-teki dan misteri. Setiap misteri disajikan dengan detail yang menarik, termasuk latar belakang sejarah, teori-teori yang ada, dan upaya-upaya untuk mengungkap kebenarannya. Pembaca akan dibawa dalam perjalanan menggali fakta dan teka-teki yang menarik dari berbagai p'),
(83, '99,99 tembus toic', 'Penerbit Utama', '2021', '99,99_ tembus toic.JPG', 'panduan kehamilan', 'Baru', 'ada', 'Buku ini adalah panduan praktis yang berisi informasi penting dan lengkap bagi ibu hamil selama 9 bulan kehamilan mereka. Mulai dari tahap awal kehamilan hingga persiapan menjelang kelahiran, buku ini memberikan pengetahuan yang dibutuhkan untuk menjalani masa kehamilan dengan sehat, aman, dan penuh kebahagiaan. Di dalamnya terdapat informasi mengenai perubahan fisik dan emosional yang terjadi pada ibu hamil, perkembangan janin, nutrisi yang dibutuhkan, olahraga yang disarankan, perawatan prenat'),
(84, '100+1cara bahagia', 'Penerbit Kesehatan Terkemuka', '2022', '100+1cara bahagia.JPG', 'panduan kesehatan', 'Bagus', 'tidak', 'Buku ini adalah panduan komprehensif yang mengulas 20 obat terpopuler yang digunakan untuk menurunkan tekanan darah tinggi (hipertensi). Setiap obat dijelaskan secara mendetail, termasuk mekanisme kerja, dosis yang direkomendasikan, efek samping yang mungkin terjadi, dan interaksi obat dengan makanan atau obat lain. Buku ini juga memberikan informasi tentang pentingnya pengelolaan tekanan darah tinggi, dampaknya terhadap kesehatan, serta saran-saran gaya hidup sehat yang dapat mendukung pengobat'),
(85, '333 dongeng binatang', 'Penerbit Sejarah Indonesia', '2021', '333 dongeng binatang.JPG', 'sejarah', 'Bekas', 'ada', 'Buku ini mengangkat kisah inspiratif dari 20 pahlawan nasional yang berperan penting dalam sejarah Indonesia. Setiap pahlawan diceritakan secara singkat dan menarik, termasuk latar belakang kehidupan, perjuangan, serta kontribusi yang mereka berikan dalam memperjuangkan kemerdekaan dan membangun negara. Buku ini menggambarkan semangat kepahlawanan, dedikasi, dan pengorbanan yang menginspirasi generasi masa kini untuk mencintai dan memperjuangkan negara mereka.'),
(86, '1001 pengetahuan moderen untuk anak', 'Penerbit Kesehatan Sehat Sentosa', '2022', '1001 pengetahuan moderen untuk anak.jpg', 'panduan kesehatan', 'Bagus', 'ada', 'Buku ini berisi 26 kiat praktis dan efektif untuk menjaga kesehatan dan kebugaran tubuh. Setiap kiat disajikan dengan penjelasan yang jelas dan ringkas, serta dilengkapi dengan langkah-langkah yang dapat diikuti untuk menerapkan kiat tersebut dalam kehidupan sehari-hari. Buku ini mencakup berbagai aspek kesehatan, seperti pola makan sehat, olahraga, tidur yang cukup, manajemen stres, dan tips untuk meningkatkan energi dan kebugaran secara keseluruhan. Dengan mengikuti kiat-kiat yang disajikan da'),
(87, 'Beternak Sapi', 'Penerbit Mysteria', '2022', '20180131_143441.jpg', 'nonfiksi', 'Baru', 'ada', 'Buku ini mengungkapkan 99 misteri terbesar yang belum terpecahkan di dunia sepanjang masa. Dari piramida Mesir kuno yang megah hingga Segitiga Bermuda yang misterius, buku ini menjelajahi berbagai kejadian dan tempat yang penuh teka-teki dan misteri. Setiap misteri disajikan dengan detail yang menarik, termasuk latar belakang sejarah, teori-teori yang ada, dan upaya-upaya untuk mengungkap kebenarannya. Pembaca akan dibawa dalam perjalanan menggali fakta dan teka-teki yang menarik dari berbagai p'),
(88, 'Buku Lama', 'Penerbit Utama', '2021', '20180201_143613.jpg', 'panduan kehamilan', 'Baru', 'ada', 'Buku ini adalah panduan praktis yang berisi informasi penting dan lengkap bagi ibu hamil selama 9 bulan kehamilan mereka. Mulai dari tahap awal kehamilan hingga persiapan menjelang kelahiran, buku ini memberikan pengetahuan yang dibutuhkan untuk menjalani masa kehamilan dengan sehat, aman, dan penuh kebahagiaan. Di dalamnya terdapat informasi mengenai perubahan fisik dan emosional yang terjadi pada ibu hamil, perkembangan janin, nutrisi yang dibutuhkan, olahraga yang disarankan, perawatan prenat'),
(89, 'buku lama 2', 'Penerbit Kesehatan Terkemuka', '2022', '20180201_144402.jpg', 'panduan kesehatan', 'Bagus', 'tidak', 'Buku ini adalah panduan komprehensif yang mengulas 20 obat terpopuler yang digunakan untuk menurunkan tekanan darah tinggi (hipertensi). Setiap obat dijelaskan secara mendetail, termasuk mekanisme kerja, dosis yang direkomendasikan, efek samping yang mungkin terjadi, dan interaksi obat dengan makanan atau obat lain. Buku ini juga memberikan informasi tentang pentingnya pengelolaan tekanan darah tinggi, dampaknya terhadap kesehatan, serta saran-saran gaya hidup sehat yang dapat mendukung pengobat'),
(90, 'buku lama 3', 'Penerbit Sejarah Indonesia', '2021', '20180201_145224.jpg', 'sejarah', 'Bekas', 'ada', 'Buku ini mengangkat kisah inspiratif dari 20 pahlawan nasional yang berperan penting dalam sejarah Indonesia. Setiap pahlawan diceritakan secara singkat dan menarik, termasuk latar belakang kehidupan, perjuangan, serta kontribusi yang mereka berikan dalam memperjuangkan kemerdekaan dan membangun negara. Buku ini menggambarkan semangat kepahlawanan, dedikasi, dan pengorbanan yang menginspirasi generasi masa kini untuk mencintai dan memperjuangkan negara mereka.'),
(91, 'Sejarah singkat dunia', 'Penerbit Kesehatan Sehat Sentosa', '2022', 'a ahort history of the world sejarah singkat dunia.JPG', 'panduan kesehatan', 'Bagus', 'ada', 'Buku ini berisi 26 kiat praktis dan efektif untuk menjaga kesehatan dan kebugaran tubuh. Setiap kiat disajikan dengan penjelasan yang jelas dan ringkas, serta dilengkapi dengan langkah-langkah yang dapat diikuti untuk menerapkan kiat tersebut dalam kehidupan sehari-hari. Buku ini mencakup berbagai aspek kesehatan, seperti pola makan sehat, olahraga, tidur yang cukup, manajemen stres, dan tips untuk meningkatkan energi dan kebugaran secara keseluruhan. Dengan mengikuti kiat-kiat yang disajikan da'),
(92, 'Sejarah CIna(CHINA)', 'Penerbit Mysteria', '2022', 'a history of china.JPG', 'nonfiksi', 'Baru', 'ada', 'Buku ini mengungkapkan 99 misteri terbesar yang belum terpecahkan di dunia sepanjang masa. Dari piramida Mesir kuno yang megah hingga Segitiga Bermuda yang misterius, buku ini menjelajahi berbagai kejadian dan tempat yang penuh teka-teki dan misteri. Setiap misteri disajikan dengan detail yang menarik, termasuk latar belakang sejarah, teori-teori yang ada, dan upaya-upaya untuk mengungkap kebenarannya. Pembaca akan dibawa dalam perjalanan menggali fakta dan teka-teki yang menarik dari berbagai p'),
(93, 'Adat isiadat daerah jambi', 'Penerbit Utama', '2021', 'adat istiadat daerah jambi.JPG', 'panduan kehamilan', 'Baru', 'ada', 'Buku ini adalah panduan praktis yang berisi informasi penting dan lengkap bagi ibu hamil selama 9 bulan kehamilan mereka. Mulai dari tahap awal kehamilan hingga persiapan menjelang kelahiran, buku ini memberikan pengetahuan yang dibutuhkan untuk menjalani masa kehamilan dengan sehat, aman, dan penuh kebahagiaan. Di dalamnya terdapat informasi mengenai perubahan fisik dan emosional yang terjadi pada ibu hamil, perkembangan janin, nutrisi yang dibutuhkan, olahraga yang disarankan, perawatan prenat'),
(94, 'agem-ageman kepemangkuan', 'Penerbit Kesehatan Terkemuka', '2022', 'agem-ageman kepemangkuan.JPG', 'panduan kesehatan', 'Bagus', 'tidak', 'Buku ini adalah panduan komprehensif yang mengulas 20 obat terpopuler yang digunakan untuk menurunkan tekanan darah tinggi (hipertensi). Setiap obat dijelaskan secara mendetail, termasuk mekanisme kerja, dosis yang direkomendasikan, efek samping yang mungkin terjadi, dan interaksi obat dengan makanan atau obat lain. Buku ini juga memberikan informasi tentang pentingnya pengelolaan tekanan darah tinggi, dampaknya terhadap kesehatan, serta saran-saran gaya hidup sehat yang dapat mendukung pengobat'),
(95, 'agis dan susu kedelai', 'Penerbit Sejarah Indonesia', '2021', 'agis dan susu kedelai.JPG', 'sejarah', 'Bekas', 'ada', 'Buku ini mengangkat kisah inspiratif dari 20 pahlawan nasional yang berperan penting dalam sejarah Indonesia. Setiap pahlawan diceritakan secara singkat dan menarik, termasuk latar belakang kehidupan, perjuangan, serta kontribusi yang mereka berikan dalam memperjuangkan kemerdekaan dan membangun negara. Buku ini menggambarkan semangat kepahlawanan, dedikasi, dan pengorbanan yang menginspirasi generasi masa kini untuk mencintai dan memperjuangkan negara mereka.'),
(96, 'agrobisnis budidaya lidah buaya', 'Penerbit Kesehatan Sehat Sentosa', '2022', 'agrobisnis budidaya lidah buaya.jpg', 'panduan kesehatan', 'Bagus', 'ada', 'Buku ini berisi 26 kiat praktis dan efektif untuk menjaga kesehatan dan kebugaran tubuh. Setiap kiat disajikan dengan penjelasan yang jelas dan ringkas, serta dilengkapi dengan langkah-langkah yang dapat diikuti untuk menerapkan kiat tersebut dalam kehidupan sehari-hari. Buku ini mencakup berbagai aspek kesehatan, seperti pola makan sehat, olahraga, tidur yang cukup, manajemen stres, dan tips untuk meningkatkan energi dan kebugaran secara keseluruhan. Dengan mengikuti kiat-kiat yang disajikan da'),
(97, 'air menurut veda bagaimana veda berbicara tenrang air di bumi', 'Penerbit Mysteria', '2022', 'air menurut veda bagaimana veda berbicara tenrang air di bumi.JPG', 'nonfiksi', 'Baru', 'ada', 'Buku ini mengungkapkan 99 misteri terbesar yang belum terpecahkan di dunia sepanjang masa. Dari piramida Mesir kuno yang megah hingga Segitiga Bermuda yang misterius, buku ini menjelajahi berbagai kejadian dan tempat yang penuh teka-teki dan misteri. Setiap misteri disajikan dengan detail yang menarik, termasuk latar belakang sejarah, teori-teori yang ada, dan upaya-upaya untuk mengungkap kebenarannya. Pembaca akan dibawa dalam perjalanan menggali fakta dan teka-teki yang menarik dari berbagai p'),
(98, 'aku bisa jika aku berpikir biasa', 'Penerbit Utama', '2021', 'aku bisa jika aku berpikir biasa.JPG', 'panduan kehamilan', 'Baru', 'ada', 'Buku ini adalah panduan praktis yang berisi informasi penting dan lengkap bagi ibu hamil selama 9 bulan kehamilan mereka. Mulai dari tahap awal kehamilan hingga persiapan menjelang kelahiran, buku ini memberikan pengetahuan yang dibutuhkan untuk menjalani masa kehamilan dengan sehat, aman, dan penuh kebahagiaan. Di dalamnya terdapat informasi mengenai perubahan fisik dan emosional yang terjadi pada ibu hamil, perkembangan janin, nutrisi yang dibutuhkan, olahraga yang disarankan, perawatan prenat'),
(99, 'akomodasi perhotelan', 'Penerbit Kesehatan Terkemuka', '2022', 'akomodasi perhotelan.jpg', 'panduan kesehatan', 'Bagus', 'tidak', 'Buku ini adalah panduan komprehensif yang mengulas 20 obat terpopuler yang digunakan untuk menurunkan tekanan darah tinggi (hipertensi). Setiap obat dijelaskan secara mendetail, termasuk mekanisme kerja, dosis yang direkomendasikan, efek samping yang mungkin terjadi, dan interaksi obat dengan makanan atau obat lain. Buku ini juga memberikan informasi tentang pentingnya pengelolaan tekanan darah tinggi, dampaknya terhadap kesehatan, serta saran-saran gaya hidup sehat yang dapat mendukung pengobat'),
(100, 'aku memilih bahagia', 'Penerbit Sejarah Indonesia', '2021', 'aku memilih bahagia.JPG', 'sejarah', 'Bekas', 'ada', 'Buku ini mengangkat kisah inspiratif dari 20 pahlawan nasional yang berperan penting dalam sejarah Indonesia. Setiap pahlawan diceritakan secara singkat dan menarik, termasuk latar belakang kehidupan, perjuangan, serta kontribusi yang mereka berikan dalam memperjuangkan kemerdekaan dan membangun negara. Buku ini menggambarkan semangat kepahlawanan, dedikasi, dan pengorbanan yang menginspirasi generasi masa kini untuk mencintai dan memperjuangkan negara mereka.'),
(101, 'aku pandai menulis cerpen', 'Penerbit Kesehatan Sehat Sentosa', '2022', 'aku pandai menulis cerpen.jpg', 'panduan kesehatan', 'Bagus', 'ada', 'Buku ini berisi 26 kiat praktis dan efektif untuk menjaga kesehatan dan kebugaran tubuh. Setiap kiat disajikan dengan penjelasan yang jelas dan ringkas, serta dilengkapi dengan langkah-langkah yang dapat diikuti untuk menerapkan kiat tersebut dalam kehidupan sehari-hari. Buku ini mencakup berbagai aspek kesehatan, seperti pola makan sehat, olahraga, tidur yang cukup, manajemen stres, dan tips untuk meningkatkan energi dan kebugaran secara keseluruhan. Dengan mengikuti kiat-kiat yang disajikan da'),
(102, 'akuntansi persahaan jasa untuk pembelajaran smk', 'Penerbit Mysteria', '2022', 'akuntansi persahaan jasa untuk pembelajaran smk.JPG', 'nonfiksi', 'Baru', 'ada', 'Buku ini mengungkapkan 99 misteri terbesar yang belum terpecahkan di dunia sepanjang masa. Dari piramida Mesir kuno yang megah hingga Segitiga Bermuda yang misterius, buku ini menjelajahi berbagai kejadian dan tempat yang penuh teka-teki dan misteri. Setiap misteri disajikan dengan detail yang menarik, termasuk latar belakang sejarah, teori-teori yang ada, dan upaya-upaya untuk mengungkap kebenarannya. Pembaca akan dibawa dalam perjalanan menggali fakta dan teka-teki yang menarik dari berbagai p'),
(103, 'alat alat praktek kerja kayu', 'Penerbit Utama', '2021', 'alat alat praktek kerja kayu.JPG', 'panduan kehamilan', 'Baru', 'ada', 'Buku ini adalah panduan praktis yang berisi informasi penting dan lengkap bagi ibu hamil selama 9 bulan kehamilan mereka. Mulai dari tahap awal kehamilan hingga persiapan menjelang kelahiran, buku ini memberikan pengetahuan yang dibutuhkan untuk menjalani masa kehamilan dengan sehat, aman, dan penuh kebahagiaan. Di dalamnya terdapat informasi mengenai perubahan fisik dan emosional yang terjadi pada ibu hamil, perkembangan janin, nutrisi yang dibutuhkan, olahraga yang disarankan, perawatan prenat'),
(104, 'alat musik tradisional nusantara', 'Penerbit Kesehatan Terkemuka', '2022', 'alat musik tradisional nusantara.JPG', 'panduan kesehatan', 'Bagus', 'tidak', 'Buku ini adalah panduan komprehensif yang mengulas 20 obat terpopuler yang digunakan untuk menurunkan tekanan darah tinggi (hipertensi). Setiap obat dijelaskan secara mendetail, termasuk mekanisme kerja, dosis yang direkomendasikan, efek samping yang mungkin terjadi, dan interaksi obat dengan makanan atau obat lain. Buku ini juga memberikan informasi tentang pentingnya pengelolaan tekanan darah tinggi, dampaknya terhadap kesehatan, serta saran-saran gaya hidup sehat yang dapat mendukung pengobat'),
(105, 'alice_s adventures in wonderland lewis caroll', 'Penerbit Sejarah Indonesia', '2021', 'alice_s adventures in wonderland lewis caroll.JPG', 'sejarah', 'Bekas', 'ada', 'Buku ini mengangkat kisah inspiratif dari 20 pahlawan nasional yang berperan penting dalam sejarah Indonesia. Setiap pahlawan diceritakan secara singkat dan menarik, termasuk latar belakang kehidupan, perjuangan, serta kontribusi yang mereka berikan dalam memperjuangkan kemerdekaan dan membangun negara. Buku ini menggambarkan semangat kepahlawanan, dedikasi, dan pengorbanan yang menginspirasi generasi masa kini untuk mencintai dan memperjuangkan negara mereka.'),
(106, 'all test masuk TNI POLRI', 'Penerbit Kesehatan Sehat Sentosa', '2022', 'all test masuk TNI POLRI.JPG', 'panduan kesehatan', 'Bagus', 'ada', 'Buku ini berisi 26 kiat praktis dan efektif untuk menjaga kesehatan dan kebugaran tubuh. Setiap kiat disajikan dengan penjelasan yang jelas dan ringkas, serta dilengkapi dengan langkah-langkah yang dapat diikuti untuk menerapkan kiat tersebut dalam kehidupan sehari-hari. Buku ini mencakup berbagai aspek kesehatan, seperti pola makan sehat, olahraga, tidur yang cukup, manajemen stres, dan tips untuk meningkatkan energi dan kebugaran secara keseluruhan. Dengan mengikuti kiat-kiat yang disajikan da'),
(107, 'alternatif bertanam', 'Penerbit Mysteria', '2022', 'alternatif bertanam .JPG', 'nonfiksi', 'Baru', 'ada', 'Buku ini mengungkapkan 99 misteri terbesar yang belum terpecahkan di dunia sepanjang masa. Dari piramida Mesir kuno yang megah hingga Segitiga Bermuda yang misterius, buku ini menjelajahi berbagai kejadian dan tempat yang penuh teka-teki dan misteri. Setiap misteri disajikan dengan detail yang menarik, termasuk latar belakang sejarah, teori-teori yang ada, dan upaya-upaya untuk mengungkap kebenarannya. Pembaca akan dibawa dalam perjalanan menggali fakta dan teka-teki yang menarik dari berbagai p'),
(108, 'anak bajang menggiring angin', 'Penerbit Utama', '2021', 'anak bajang menggiring angin.jpg', 'panduan kehamilan', 'Baru', 'ada', 'Buku ini adalah panduan praktis yang berisi informasi penting dan lengkap bagi ibu hamil selama 9 bulan kehamilan mereka. Mulai dari tahap awal kehamilan hingga persiapan menjelang kelahiran, buku ini memberikan pengetahuan yang dibutuhkan untuk menjalani masa kehamilan dengan sehat, aman, dan penuh kebahagiaan. Di dalamnya terdapat informasi mengenai perubahan fisik dan emosional yang terjadi pada ibu hamil, perkembangan janin, nutrisi yang dibutuhkan, olahraga yang disarankan, perawatan prenat'),
(109, 'aneka cara pembibitan ikan 63', 'Penerbit Kesehatan Terkemuka', '2022', 'aneka cara pembibitan ikan 63.jpg', 'panduan kesehatan', 'Bagus', 'tidak', 'Buku ini adalah panduan komprehensif yang mengulas 20 obat terpopuler yang digunakan untuk menurunkan tekanan darah tinggi (hipertensi). Setiap obat dijelaskan secara mendetail, termasuk mekanisme kerja, dosis yang direkomendasikan, efek samping yang mungkin terjadi, dan interaksi obat dengan makanan atau obat lain. Buku ini juga memberikan informasi tentang pentingnya pengelolaan tekanan darah tinggi, dampaknya terhadap kesehatan, serta saran-saran gaya hidup sehat yang dapat mendukung pengobat'),
(110, 'aneka cara pembibitan tanaman 62', 'Penerbit Sejarah Indonesia', '2021', 'aneka cara pembibitan tanaman 62.JPG', 'sejarah', 'Bekas', 'ada', 'Buku ini mengangkat kisah inspiratif dari 20 pahlawan nasional yang berperan penting dalam sejarah Indonesia. Setiap pahlawan diceritakan secara singkat dan menarik, termasuk latar belakang kehidupan, perjuangan, serta kontribusi yang mereka berikan dalam memperjuangkan kemerdekaan dan membangun negara. Buku ini menggambarkan semangat kepahlawanan, dedikasi, dan pengorbanan yang menginspirasi generasi masa kini untuk mencintai dan memperjuangkan negara mereka.'),
(111, 'aneka dari olahan daging', 'Penerbit Kesehatan Sehat Sentosa', '2022', 'aneka dari olahan daging.JPG', 'panduan kesehatan', 'Bagus', 'ada', 'Buku ini berisi 26 kiat praktis dan efektif untuk menjaga kesehatan dan kebugaran tubuh. Setiap kiat disajikan dengan penjelasan yang jelas dan ringkas, serta dilengkapi dengan langkah-langkah yang dapat diikuti untuk menerapkan kiat tersebut dalam kehidupan sehari-hari. Buku ini mencakup berbagai aspek kesehatan, seperti pola makan sehat, olahraga, tidur yang cukup, manajemen stres, dan tips untuk meningkatkan energi dan kebugaran secara keseluruhan. Dengan mengikuti kiat-kiat yang disajikan da'),
(112, 'aneka dari olahan jagung', 'Penerbit Mysteria', '2022', 'aneka dari olahan jagung.JPG', 'nonfiksi', 'Baru', 'ada', 'Buku ini mengungkapkan 99 misteri terbesar yang belum terpecahkan di dunia sepanjang masa. Dari piramida Mesir kuno yang megah hingga Segitiga Bermuda yang misterius, buku ini menjelajahi berbagai kejadian dan tempat yang penuh teka-teki dan misteri. Setiap misteri disajikan dengan detail yang menarik, termasuk latar belakang sejarah, teori-teori yang ada, dan upaya-upaya untuk mengungkap kebenarannya. Pembaca akan dibawa dalam perjalanan menggali fakta dan teka-teki yang menarik dari berbagai p'),
(113, 'aneka gerabah', 'Penerbit Utama', '2021', 'aneka gerabah.JPG', 'panduan kehamilan', 'Baru', 'ada', 'Buku ini adalah panduan praktis yang berisi informasi penting dan lengkap bagi ibu hamil selama 9 bulan kehamilan mereka. Mulai dari tahap awal kehamilan hingga persiapan menjelang kelahiran, buku ini memberikan pengetahuan yang dibutuhkan untuk menjalani masa kehamilan dengan sehat, aman, dan penuh kebahagiaan. Di dalamnya terdapat informasi mengenai perubahan fisik dan emosional yang terjadi pada ibu hamil, perkembangan janin, nutrisi yang dibutuhkan, olahraga yang disarankan, perawatan prenat'),
(114, 'aneka hidangan mi dan pasta', 'Penerbit Kesehatan Terkemuka', '2022', 'aneka hidangan mi dan pasta.JPG', 'panduan kesehatan', 'Bagus', 'tidak', 'Buku ini adalah panduan komprehensif yang mengulas 20 obat terpopuler yang digunakan untuk menurunkan tekanan darah tinggi (hipertensi). Setiap obat dijelaskan secara mendetail, termasuk mekanisme kerja, dosis yang direkomendasikan, efek samping yang mungkin terjadi, dan interaksi obat dengan makanan atau obat lain. Buku ini juga memberikan informasi tentang pentingnya pengelolaan tekanan darah tinggi, dampaknya terhadap kesehatan, serta saran-saran gaya hidup sehat yang dapat mendukung pengobat'),
(115, 'aneka kebaya tradisional dan modern', 'Penerbit Sejarah Indonesia', '2021', 'aneka kebaya tradisional dan modern.JPG', 'sejarah', 'Bekas', 'ada', 'Buku ini mengangkat kisah inspiratif dari 20 pahlawan nasional yang berperan penting dalam sejarah Indonesia. Setiap pahlawan diceritakan secara singkat dan menarik, termasuk latar belakang kehidupan, perjuangan, serta kontribusi yang mereka berikan dalam memperjuangkan kemerdekaan dan membangun negara. Buku ini menggambarkan semangat kepahlawanan, dedikasi, dan pengorbanan yang menginspirasi generasi masa kini untuk mencintai dan memperjuangkan negara mereka.'),
(116, 'aneka kerajinan payet seni kreasi ayet unik dan menarik', 'Penerbit Kesehatan Sehat Sentosa', '2022', 'aneka kerajinan payet seni kreasi ayet unik dan menarik.JPG', 'panduan kesehatan', 'Bagus', 'ada', 'Buku ini berisi 26 kiat praktis dan efektif untuk menjaga kesehatan dan kebugaran tubuh. Setiap kiat disajikan dengan penjelasan yang jelas dan ringkas, serta dilengkapi dengan langkah-langkah yang dapat diikuti untuk menerapkan kiat tersebut dalam kehidupan sehari-hari. Buku ini mencakup berbagai aspek kesehatan, seperti pola makan sehat, olahraga, tidur yang cukup, manajemen stres, dan tips untuk meningkatkan energi dan kebugaran secara keseluruhan. Dengan mengikuti kiat-kiat yang disajikan da'),
(117, 'aneka konstruksi kerajinan tangan', 'Penerbit Mysteria', '2022', 'aneka konstruksi kerajinan tangan.JPG', 'nonfiksi', 'Baru', 'ada', 'Buku ini mengungkapkan 99 misteri terbesar yang belum terpecahkan di dunia sepanjang masa. Dari piramida Mesir kuno yang megah hingga Segitiga Bermuda yang misterius, buku ini menjelajahi berbagai kejadian dan tempat yang penuh teka-teki dan misteri. Setiap misteri disajikan dengan detail yang menarik, termasuk latar belakang sejarah, teori-teori yang ada, dan upaya-upaya untuk mengungkap kebenarannya. Pembaca akan dibawa dalam perjalanan menggali fakta dan teka-teki yang menarik dari berbagai p'),
(118, 'Aneka Kue dan Roti', 'contoh', 'contoh', 'Aneka Kue dan Roti.JPG', 'contoh', 'Bekas', 'tidak', 'contoh'),
(119, 'Aneka masakan dan minuman', 'contoh', 'contoh', 'aneka masakan dan minuman.JPG', 'contoh', 'Baru', 'tidak', 'contoh'),
(120, 'aneka minuman chas daerah', 'contoh', 'contoh', 'aneka minuman khas daerah.JPG', 'contoh', 'Bagus', 'tidak', 'contoh'),
(121, 'aneka motif tenun', 'contoh', 'contoh', 'aneka motif tenun dari benang agel.JPG', 'contoh', 'Bekas', 'ada', 'contoh'),
(122, 'aneka olahan tepung', 'contoh', 'contoh', 'aneka olahan tepung.JPG', 'contoh', 'Baru', 'ada', 'contoh'),
(123, 'aneka olahan umbi', 'contoh', 'contoh', 'aneka olahan umbi umbian.JPG', 'contoh', 'Baru', 'tidak', 'contoh'),
(124, 'ubi kayu', 'contoh', 'contoh', 'aneka produk olahan ubi kayu.JPG', 'contoh', 'Bagus', 'ada', 'contoh');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `perpustakaan`
--
ALTER TABLE `perpustakaan`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `perpustakaan`
--
ALTER TABLE `perpustakaan`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=126;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
